Airflow and docker setup (#14)
- Docker configuration for elk-only, elk+pg+fastapi, and elk+pg+fastapi+redis+airflow, including es/kibana certs setup, directory mounts, healthchecks, .env file tweaks for port, volume, & network setup
- Airflow docker container build via image extension, enabling transcript-playground project libs and deps to be mounted/built/included in path on airflow container
- Bare-bones airflow dag setup for full fastapi-driven ETL chain: 
  - copy external episode listing and transcript text to files
  - ingest episode metadata and transcript text to db
  - load episode transcript db to es
  - load topics data to es
  - load speaker metadata to es
  - generate embeddings against transcripts, topics, and speaker dialog (refactor handling of openai BadRequestError exceeding max tokens)
  - map episodes to episodes, episodes to topics, and speakers to topics
  - generate speaker sentiment at episode-level and scene-level (line-level and nltk polaritt temporarily disabled)
  - populate episode sub-narratives
  - publish wordclouds
  - publish speaker bar chart animations
- Move ETL and process trigger functionality out of standalone scripts and into data_service modules where they can be triggered by airflow dags and/or bare-bones command-line scripts (now in scripts/ dir)
- Reconfigure published wordclouds and animations to live in static/ dir, move generated resource files (e.g. Bertopic and sentiment csv files) into generated_data/ dir
- Fully phase out legacy dash configs, migrate Bertopic 3D scatters (and episode sub-narrative dependencies/pages) out of legacy dash into new dash multi-page layouts
- Minor changes to es schema to support index ground-up index refresh, minor code changes to exclude 'focused' and 'universal genres gpt3 v2' topics
- Incorporate openai 3small model into embeddings ETL pipelines 
- Limit async/await calls to tortoise, remove from es r/w and other actions
- Comment out usage of diskcache / DiskcacheManager / background_callback_manager

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -1,8 +1,67 @@
-version: '3.8'
+volumes:
+  pgdata1028:
+    driver: local
+  certs:
+    driver: local
+  esdata1028:
+    driver: local
+  kibanadata:
+    driver: local
+    
+    
+networks:
+ default:
+   name: esnet1028
+   external: false
+
+
+x-airflow-common:
+  &airflow-common
+  # In order to add custom dependencies or upgrade provider packages you can use your extended image.
+  # Comment the image line, place your Dockerfile in the directory where you placed the docker-compose.yaml
+  # and uncomment the "build" line below, Then run `docker-compose build` to build the images.
+  # image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.10.2}
+  build:
+    context: .
+    dockerfile: DockerfileAirflow
+  environment:
+    &airflow-common-env
+    PYTHONPATH: /opt/airflow/extensions:${PYTHONPATH}
+    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
+    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${PG_USER}:${PG_PASSWORD}@${PG_HOST}:${PG_PORT}/${PG_DB_NAME}
+    # For backward compatibility, with Airflow <2.3
+    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${PG_USER}:${PG_PASSWORD}@${PG_HOST}:${PG_PORT}/${PG_DB_NAME}
+    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${PG_USER}:${PG_PASSWORD}@${PG_HOST}:${PG_PORT}/${PG_DB_NAME}
+    AIRFLOW__CELERY__BROKER_URL: redis://:@redis1028:6379/0
+    AIRFLOW__CORE__FERNET_KEY: ''
+    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
+    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
+    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
+    DATABASE_URL: postgres://${PG_USER}:${PG_PASSWORD}@${PG_HOST}:${PG_PORT}/${PG_DB_NAME}
+    _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-}
+  volumes:
+    - ${AIRFLOW_PROJ_DIR:-.}/dags:/opt/airflow/dags
+    - ${AIRFLOW_PROJ_DIR:-.}/logs:/opt/airflow/logs
+    - ${AIRFLOW_PROJ_DIR:-.}/plugins:/opt/airflow/plugins
+    # - ./entrypoint.sh:/entrypoint.sh
+    # - ./requirements.txt:/requirements.txt
+    - ${AIRFLOW_PROJ_DIR:-.}/app:/opt/airflow/extensions/app
+    - ${AIRFLOW_PROJ_DIR:-.}/static:/opt/airflow/static
+    - ${AIRFLOW_PROJ_DIR:-.}/generated_data:/opt/airflow/generated_data
+    - .env:/opt/airflow/.env
+  user: "${AIRFLOW_UID:-50000}:0"
+  # entrypoint: /entrypoint.sh
+  depends_on:
+    &airflow-common-depends-on
+    redis1028:
+      condition: service_healthy
+    pg1028:
+      condition: service_healthy
+
 
 services:
-  setup:
-    container_name: setupTrp
+  elk-setup:
+    container_name: container-elk-setup
     image: docker.elastic.co/elasticsearch/elasticsearch:${ES_STACK_VERSION}
     volumes:
       - certs:/usr/share/elasticsearch/config/certs
@@ -31,6 +90,12 @@ services:
           "      - localhost\n"\
           "    ip:\n"\
           "      - 127.0.0.1\n"\
+          "  - name: ${KB_HOST}\n"\
+          "    dns:\n"\
+          "      - ${KB_HOST}\n"\
+          "      - localhost\n"\
+          "    ip:\n"\
+          "      - 127.0.0.1\n"\
           > config/certs/instances.yml;
           bin/elasticsearch-certutil cert --silent --pem -out config/certs/certs.zip --in config/certs/instances.yml --ca-cert config/certs/ca/ca.crt --ca-key config/certs/ca/ca.key;
           unzip config/certs/certs.zip -d config/certs;
@@ -40,9 +105,9 @@ services:
         find . -type d -exec chmod 750 \{\} \;;
         find . -type f -exec chmod 640 \{\} \;;
         echo "Waiting for Elasticsearch availability";
-        until curl -s --cacert config/certs/ca/ca.crt https://${ES_HOST}:${ES_PORT} | grep -q "missing authentication credentials"; do sleep 30; done;
+        until curl -s --cacert config/certs/ca/ca.crt https://${ES_HOST}:9200 | grep -q "missing authentication credentials"; do sleep 30; done;
         echo "Setting kibana_system password";
-        until curl -s -X POST --cacert config/certs/ca/ca.crt -u "elastic:${ES_PASSWORD}" -H "Content-Type: application/json" https://${ES_HOST}:${ES_PORT}/_security/user/kibana_system/_password -d "{\"password\":\"${KB_PASSWORD}\"}" | grep -q "^{}"; do sleep 10; done;
+        until curl -s -X POST --cacert config/certs/ca/ca.crt -u "elastic:${ES_PASSWORD}" -H "Content-Type: application/json" https://${ES_HOST}:9200/_security/user/kibana_system/_password -d "{\"password\":\"${KB_PASSWORD}\"}" | grep -q "^{}"; do sleep 10; done;
         echo "All done!";
       '
     healthcheck:
@@ -50,14 +115,16 @@ services:
       interval: 1s
       timeout: 5s
       retries: 120
-  pg:
-    container_name: ${PG_HOST}
+
+
+  pg1028:
+    container_name: container-pg1028
     image: postgres:15-alpine
     restart: always
     ports:
       - "${PG_PORT}:${PG_PORT}"
     volumes:
-      - postgres_data:/var/lib/postgresql/data/
+      - pgdata1028:/var/lib/postgresql/data/
     expose:
       - ${PG_PORT}
     command: postgres -c port=${PG_PORT}
@@ -65,22 +132,42 @@ services:
       POSTGRES_USER: ${PG_USER}
       POSTGRES_PASSWORD: ${PG_PASSWORD}
       POSTGRES_DB: ${PG_DB_NAME}
+      PGUSER: ${PG_USER}
+    healthcheck:
+      test: [ "CMD-SHELL", "pg_isready -d ${PG_DB_NAME} -U ${PG_USER}" ]
+      interval: 5s
+      retries: 5
     # command:
     #   - "postgres"
     #   - "-c"
     #   - "listen_addresses=*"
-  es:
-    container_name: ${ES_HOST}
+
+
+  redis1028:
+    container_name: container-redis1028
+    image: redis:latest
+    expose:
+      - 6379
+    healthcheck:
+      test: ["CMD", "redis-cli", "ping"]
+      interval: 5s
+      timeout: 30s
+      retries: 50
+    restart: always
+
+
+  es1028:
+    container_name: container-es1028
     depends_on:
-      setup:
+      elk-setup:
         condition: service_healthy
     image: docker.elastic.co/elasticsearch/elasticsearch:${ES_STACK_VERSION}
     volumes:
       - certs:/usr/share/elasticsearch/config/certs
-      - esdata02:/usr/share/elasticsearch/data
+      - esdata1028:/usr/share/elasticsearch/data
       # - ./elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml
     ports:
-      - ${ES_PORT}:${ES_PORT}
+      - ${ES_PORT}:9200
     environment:
       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
       - MAX_LOCKED_MEMORY=unlimited
@@ -111,15 +198,17 @@ services:
       test:
         [
           "CMD-SHELL",
-          "curl -s --cacert config/certs/ca/ca.crt https://localhost:${ES_PORT} | grep -q 'missing authentication credentials'",
+          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
         ]
       interval: 5s
       timeout: 5s
       retries: 5
-  kib:
-    container_name: kibTrp
+
+
+  kib1028:
+    container_name: container-kib1028
     depends_on:
-      es:
+      es1028:
         condition: service_healthy
     image: docker.elastic.co/kibana/kibana:${ES_STACK_VERSION}
     volumes:
@@ -143,8 +232,224 @@ services:
       interval: 5s
       timeout: 5s
       retries: 5
+
+
+  airflow-init:
+    <<: *airflow-common
+    container_name: container-af-init
+    entrypoint: /bin/bash
+    # yamllint disable rule:line-length
+    command:
+      - -c
+      - |
+        # TODO copied from tutorial, can't handle v2.10, must compare on string 
+        # function ver() {
+        #   printf "%04d%04d%04d%04d" $${1//./ }
+        # }
+        # airflow_version=$$(AIRFLOW__LOGGING__LOGGING_LEVEL=INFO && gosu airflow airflow version)
+        # airflow_version_comparable=$$(ver $${airflow_version})
+        # min_airflow_version=2.2.0
+        # min_airflow_version_comparable=$$(ver $${min_airflow_version})
+        # if (( airflow_version_comparable < min_airflow_version_comparable )); then
+        #   echo
+        #   echo -e "\033[1;31mERROR!!!: Too old Airflow version $${airflow_version}!\e[0m"
+        #   echo "The minimum Airflow version supported: $${min_airflow_version}. Only use this or higher!"
+        #   echo
+        #   exit 1
+        # fi
+        if [[ -z "${AIRFLOW_UID}" ]]; then
+          echo
+          echo -e "\033[1;33mWARNING!!!: AIRFLOW_UID not set!\e[0m"
+          echo "If you are on Linux, you SHOULD follow the instructions below to set "
+          echo "AIRFLOW_UID environment variable, otherwise files will be owned by root."
+          echo "For other operating systems you can get rid of the warning with manually created .env file:"
+          echo "    See: https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#setting-the-right-airflow-user"
+          echo
+        fi
+        one_meg=1048576
+        mem_available=$$(($$(getconf _PHYS_PAGES) * $$(getconf PAGE_SIZE) / one_meg))
+        cpus_available=$$(grep -cE 'cpu[0-9]+' /proc/stat)
+        disk_available=$$(df / | tail -1 | awk '{print $$4}')
+        warning_resources="false"
+        if (( mem_available < 4000 )) ; then
+          echo
+          echo -e "\033[1;33mWARNING!!!: Not enough memory available for Docker.\e[0m"
+          echo "At least 4GB of memory required. You have $$(numfmt --to iec $$((mem_available * one_meg)))"
+          echo
+          warning_resources="true"
+        fi
+        if (( cpus_available < 2 )); then
+          echo
+          echo -e "\033[1;33mWARNING!!!: Not enough CPUS available for Docker.\e[0m"
+          echo "At least 2 CPUs recommended. You have $${cpus_available}"
+          echo
+          warning_resources="true"
+        fi
+        if (( disk_available < one_meg * 10 )); then
+          echo
+          echo -e "\033[1;33mWARNING!!!: Not enough Disk space available for Docker.\e[0m"
+          echo "At least 10 GBs recommended. You have $$(numfmt --to iec $$((disk_available * 1024 )))"
+          echo
+          warning_resources="true"
+        fi
+        if [[ $${warning_resources} == "true" ]]; then
+          echo
+          echo -e "\033[1;33mWARNING!!!: You have not enough resources to run Airflow (see above)!\e[0m"
+          echo "Please follow the instructions to increase amount of resources available:"
+          echo "   https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#before-you-begin"
+          echo
+        fi
+        mkdir -p /sources/logs /sources/dags /sources/plugins
+        chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins}
+        exec /entrypoint airflow version
+    # yamllint enable rule:line-length
+    environment:
+      <<: *airflow-common-env
+      _AIRFLOW_DB_UPGRADE: 'true'
+      _AIRFLOW_WWW_USER_CREATE: 'true'
+      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
+      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
+      _PIP_ADDITIONAL_REQUIREMENTS: ''
+    user: "0:0"
+    volumes:
+      - ${AIRFLOW_PROJ_DIR:-.}:/sources
+
+
+  airflow-webserver:
+    <<: *airflow-common
+    container_name: container-af-webserver
+    command: webserver
+    ports:
+      - 8080:8080
+    healthcheck:
+      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
+      interval: 10s
+      timeout: 10s
+      retries: 5
+    restart: always
+    depends_on:
+      <<: *airflow-common-depends-on
+      airflow-init:
+        condition: service_completed_successfully
+
+
+  airflow-scheduler:
+    <<: *airflow-common
+    container_name: container-af-scheduler
+    command: scheduler
+    healthcheck:
+      test: ["CMD-SHELL", 'airflow jobs check --job-type SchedulerJob --hostname "$${HOSTNAME}"']
+      interval: 10s
+      timeout: 10s
+      retries: 5
+    restart: always
+    depends_on:
+      <<: *airflow-common-depends-on
+      airflow-init:
+        condition: service_completed_successfully
+
+
+  airflow-worker:
+    <<: *airflow-common
+    container_name: container-af-worker
+    command: celery worker
+    healthcheck:
+      test:
+        - "CMD-SHELL"
+        - 'celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
+      interval: 10s
+      timeout: 10s
+      retries: 5
+    environment:
+      <<: *airflow-common-env
+      # Required to handle warm shutdown of the celery workers properly
+      # See https://airflow.apache.org/docs/docker-stack/entrypoint.html#signal-propagation
+      DUMB_INIT_SETSID: "0"
+    restart: always
+    depends_on:
+      <<: *airflow-common-depends-on
+      airflow-init:
+        condition: service_completed_successfully
+
+
+  # airflow-worker-2:
+  #   <<: *airflow-common
+  #   command: celery worker -q high_cpu
+  #   healthcheck:
+  #     test:
+  #       - "CMD-SHELL"
+  #       - 'celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
+  #     interval: 10s
+  #     timeout: 10s
+  #     retries: 5
+  #   environment:
+  #     <<: *airflow-common-env
+  #     # Required to handle warm shutdown of the celery workers properly
+  #     # See https://airflow.apache.org/docs/docker-stack/entrypoint.html#signal-propagation
+  #     DUMB_INIT_SETSID: "0"
+  #   restart: always
+  #   depends_on:
+  #     <<: *airflow-common-depends-on
+  #     airflow-init:
+  #       condition: service_completed_successfully
+
+
+  airflow-triggerer:
+    <<: *airflow-common
+    container_name: container-af-triggerer
+    command: triggerer
+    healthcheck:
+      test: ["CMD-SHELL", 'airflow jobs check --job-type TriggererJob --hostname "$${HOSTNAME}"']
+      interval: 10s
+      timeout: 10s
+      retries: 5
+    restart: always
+    depends_on:
+      <<: *airflow-common-depends-on
+      airflow-init:
+        condition: service_completed_successfully
+
+
+  airflow-cli:
+    <<: *airflow-common
+    container_name: container-af-cli
+    profiles:
+      - debug
+    environment:
+      <<: *airflow-common-env
+      CONNECTION_CHECK_MAX_COUNT: "0"
+    # Workaround for entrypoint issue. See: https://github.com/apache/airflow/issues/16252
+    command:
+      - bash
+      - -c
+      - airflow
+
+
+  # You can enable flower by adding "--profile flower" option e.g. docker-compose --profile flower up
+  # or by explicitly targeted on the command line e.g. docker-compose up flower.
+  # See: https://docs.docker.com/compose/profiles/
+  flower:
+    <<: *airflow-common
+    container_name: container-flower
+    command: celery flower
+    profiles:
+      - flower
+    ports:
+      - 5555:5555
+    healthcheck:
+      test: ["CMD", "curl", "--fail", "http://localhost:5555/"]
+      interval: 10s
+      timeout: 10s
+      retries: 5
+    restart: always
+    depends_on:
+      <<: *airflow-common-depends-on
+      airflow-init:
+        condition: service_completed_successfully
+
+
   web:
-    container_name: webTrp
+    container_name: container-web
     build:
         context: .
         dockerfile: Dockerfile
@@ -156,20 +461,5 @@ services:
     environment:
       DATABASE_URL: postgres://${PG_USER}:${PG_PASSWORD}@${PG_HOST}:${PG_PORT}/${PG_DB_NAME}
     depends_on:
-      - pg
-      - es
-
-volumes:
-  postgres_data:
-    driver: local
-  certs:
-    driver: local
-  esdata02:
-    driver: local
-  kibanadata:
-    driver: local
-
-networks:
- default:
-   name: esnet
-   external: false
+      - pg1028
+      - es1028
