airflow docker build using image extension, enabling all transcript-playground project libs and deps to be mounted/built/included in path on airflow container; also minimize async/await calls to tortoise (which requires them)

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -20,10 +20,13 @@ x-airflow-common:
   # In order to add custom dependencies or upgrade provider packages you can use your extended image.
   # Comment the image line, place your Dockerfile in the directory where you placed the docker-compose.yaml
   # and uncomment the "build" line below, Then run `docker-compose build` to build the images.
-  image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.5.1}
-  # build: .
+  # image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.10.2}
+  build:
+    context: .
+    dockerfile: DockerfileAirflow
   environment:
     &airflow-common-env
+    PYTHONPATH: /opt/airflow/extensions:${PYTHONPATH}
     AIRFLOW__CORE__EXECUTOR: CeleryExecutor
     AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${PG_USER}:${PG_PASSWORD}@${PG_HOST}:${PG_PORT}/${PG_DB_NAME}
     # For backward compatibility, with Airflow <2.3
@@ -34,12 +37,19 @@ x-airflow-common:
     AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
     AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
     AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
+    DATABASE_URL: postgres://${PG_USER}:${PG_PASSWORD}@${PG_HOST}:${PG_PORT}/${PG_DB_NAME}
     _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-}
+    # _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:- aerich==0.7.2 asyncpg==0.28.0 bertopic==0.16.0 bs4==0.0.1 dash==2.15.0 dash-bootstrap-components==1.5.0 dash-core-components==2.0.0 dash-html-components==2.0.0 dash-table==5.0.0 elasticsearch==8.8.0 elasticsearch-dsl==8.9.0 fastapi==0.103.2 gensim==4.2.0 html5lib==1.1 http-exceptions==0.2.10 igraph==0.10.8 jinja2==3.0.2 lxml==4.9.3 matplotlib==3.5.3 networkx==2.6.3 nltk==3.8.1 numpy==1.21.6 openai==1.6.1 pandas==1.3.5 plotly==5.18.0 pydantic==2.3.0 pydantic_core==2.6.3 pydantic-extra-types==2.1.0 pydantic-settings==2.0.3 pytest==7.4.4 pytest-asyncio==0.21.2 python-multipart==0.0.6 requests==2.30.0 scikit-learn==1.0.2 scipy==1.7.3 tortoise-orm==0.19.3 uvicorn==0.22.0  urllib3==1.26.15 }  
   volumes:
     - ${AIRFLOW_PROJ_DIR:-.}/dags:/opt/airflow/dags
     - ${AIRFLOW_PROJ_DIR:-.}/logs:/opt/airflow/logs
     - ${AIRFLOW_PROJ_DIR:-.}/plugins:/opt/airflow/plugins
+    # - ./entrypoint.sh:/entrypoint.sh
+    # - ./requirements.txt:/requirements.txt
+    - ${AIRFLOW_PROJ_DIR:-.}/app:/opt/airflow/extensions/app
+    - .env:/opt/airflow/.env
   user: "${AIRFLOW_UID:-50000}:0"
+  # entrypoint: /entrypoint.sh
   depends_on:
     &airflow-common-depends-on
     redis1028:
@@ -231,20 +241,21 @@ services:
     command:
       - -c
       - |
-        function ver() {
-          printf "%04d%04d%04d%04d" $${1//./ }
-        }
-        airflow_version=$$(AIRFLOW__LOGGING__LOGGING_LEVEL=INFO && gosu airflow airflow version)
-        airflow_version_comparable=$$(ver $${airflow_version})
-        min_airflow_version=2.2.0
-        min_airflow_version_comparable=$$(ver $${min_airflow_version})
-        if (( airflow_version_comparable < min_airflow_version_comparable )); then
-          echo
-          echo -e "\033[1;31mERROR!!!: Too old Airflow version $${airflow_version}!\e[0m"
-          echo "The minimum Airflow version supported: $${min_airflow_version}. Only use this or higher!"
-          echo
-          exit 1
-        fi
+        # TODO copied from tutorial, can't handle v2.10, must compare on string 
+        # function ver() {
+        #   printf "%04d%04d%04d%04d" $${1//./ }
+        # }
+        # airflow_version=$$(AIRFLOW__LOGGING__LOGGING_LEVEL=INFO && gosu airflow airflow version)
+        # airflow_version_comparable=$$(ver $${airflow_version})
+        # min_airflow_version=2.2.0
+        # min_airflow_version_comparable=$$(ver $${min_airflow_version})
+        # if (( airflow_version_comparable < min_airflow_version_comparable )); then
+        #   echo
+        #   echo -e "\033[1;31mERROR!!!: Too old Airflow version $${airflow_version}!\e[0m"
+        #   echo "The minimum Airflow version supported: $${min_airflow_version}. Only use this or higher!"
+        #   echo
+        #   exit 1
+        # fi
         if [[ -z "${AIRFLOW_UID}" ]]; then
           echo
           echo -e "\033[1;33mWARNING!!!: AIRFLOW_UID not set!\e[0m"
